### ISSUE TITLE
Attributes

### ISSUE THREAD

**Issue by alexfish** [ustwo/objective-c-style-guide#8]
Could be useful to add a section on usage of `__attribute__` compiler directives, when to use them & common uses.

Resources:
http://nshipster.com/__attribute__/
https://blog.twitter.com/2014/attribute-directives-in-objective-c

Would we say this is a matter of style or is this tipping into more of a general good practice guidleline?

**Comment by martinstolz** [comment]
Grey area. Probably more a good practice.

**Comment by KATT** [comment]
Why not add an `Extras.md` or a snippets folder with good practises?

**Comment by alexfish** [comment]
That could work, I agree this isn't one for the style guide
